/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-COM4D.h
 #	source generated by 4D Plugin Wizard
 #	Project : COM4D
 #	author : miyako
 #	2020/03/19
 #  
 # --------------------------------------------------------------------------------*/

#ifndef ICHIGOCOMHELPER_H
#define ICHIGOCOMHELPER_H

#include <windows.h>    // advapi32.lib
#include <rpc.h>        // rpcrt4.lib
#include <string>
#include <fstream>
#include <sstream>
#include <algorithm>

HRESULT
suppLogFileAppendW(LPCWSTR pszFileNameW, const void* pv, ULONG cb,
	ULONG* pcbWritten = NULL); //throw()

std::wstring
suppGetModuleFileName(HINSTANCE hinst);

std::wstring
suppGuidToString(const GUID& rguid, bool brackets_flag);

bool
suppIsPerUserRequest(LPCWSTR pwszCmdline); //throw()

std::wstring
suppGetRegKey(HKEY* phkeyRoot, bool per_user_flag);

std::wstring
suppGetRegKeyGUID(HKEY* phkeyRoot, bool per_user_flag, const GUID& rguid,
	LPCWSTR pwszGUIDType, LPCWSTR pwszSubkey);

std::wstring
suppGetRegKeyProgID(HKEY* phkeyRoot, bool per_user_flag,
	LPCWSTR pwszProgID, LPCWSTR pwszSubkey);

std::wstring
suppGetRegKeyAppID(HKEY* phkeyRoot, bool per_user_flag,
	const CLSID& rappid, LPCWSTR pwszSubkey);

std::wstring
suppGetRegKeyCLSID(HKEY* phkeyRoot, bool per_user_flag,
	const CLSID& rclsid, LPCWSTR pwszSubkey);

std::wstring
suppGetRegKeyInterface(HKEY* phkeyRoot, bool per_user_flag,
	const IID& riid, LPCWSTR pwszSubkey);

LONG
suppRegSetStringW(HKEY hkeyRoot, LPCWSTR pwszSubkey,
	LPCWSTR pwszValueName, LPCWSTR pwszValue);

LONG
suppRegRemoveKeyW(HKEY hkeyRoot, LPCWSTR pwszKey); //throw()

#endif /* ICHIGOCOMHELPER_H */
